<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>LethalLevelLoader</AssemblyName>
    <Description>A Custom API to support the manual and dynamic integration of custom levels and dungeons in Lethal Company.</Description>
    <Version>1.7.6</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>preview</LangVersion>

    <PackageId>IAmBatby.$(AssemblyName)</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IsPackable>true</IsPackable>

    <RootNamespace>$(AssemblyName)</RootNamespace>
    <PackageIcon>icon.png</PackageIcon>

    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/IAmBatby/LethalLevelLoader/</RepositoryUrl>
    <PackageProjectUrl>$(RepositoryUrl)</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>

    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
    <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=./</PathMap>

  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.*" PrivateAssets="all" />
  </ItemGroup>

  <!-- Code linting. -->
  <PropertyGroup>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <AnalysisMode>All</AnalysisMode>
    <AnalysisLevel>preview-recommended</AnalysisLevel>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(ProjectDir)../README.md" Pack="true" PackagePath="/" />
    <None Include="$(ProjectDir)../icon.png" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DiFFoZ-LethalPerformance" Version="1.2.*" PrivateAssets="all" Publicize="true" />
    <PackageReference Include="Evaisa.LethalLib" Version="1.2.*" PrivateAssets="all" Publicize="true" />
    <PackageReference Include="TeamXiaolan.DawnLib" Version="0.9.*" PrivateAssets="all" />
    <PackageReference Include="MinVer" Version="4.*" PrivateAssets="all" Private="false" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="VanillaContentTags\Enemies.csv" />
    <None Remove="VanillaContentTags\Items.csv" />
    <None Remove="VanillaContentTags\SelectableLevels.csv" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="VanillaContentTags\Enemies.csv" />
    <EmbeddedResource Include="VanillaContentTags\Items.csv" />
    <EmbeddedResource Include="VanillaContentTags\SelectableLevels.csv" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Unity.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaxWasUnavailable.LethalModDataLib" Version="1.2.2" PrivateAssets="all" />
    <PackageReference Include="LethalCompany.GameLibs.Steam" Version="81.0.5-ngd.0" PrivateAssets="all" Publicize="true" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LethalLevelLoader.Patcher\LethalLevelLoader.Patcher.csproj">
      <PrivateAssets>all</PrivateAssets>
      <Name>LethalLevelLoader.Patcher</Name>
      <ReferenceOutputAssembly>true</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>

  <Target Name="NetcodePatch" AfterTargets="PostBuildEvent">
    <PropertyGroup>
      <NetcodePatcherDepsListFile>$(IntermediateOutputPath)ncp-deps.list</NetcodePatcherDepsListFile>
    </PropertyGroup>
    <WriteLinesToFile File="$(NetcodePatcherDepsListFile)" Lines="@(ReferencePathWithRefAssemblies)" Overwrite="true"/>
    <Exec Command="dotnet netcode-patch -uv 2022.3.62 -nv 1.12.2 -tv 1.0.0 &quot;$(TargetPath)&quot; --dependency-file &quot;$(NetcodePatcherDepsListFile)&quot;" />
  </Target>

  <PropertyGroup>
    <MinVerDefaultPreReleaseIdentifiers>dev</MinVerDefaultPreReleaseIdentifiers>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
  </PropertyGroup>

  <Target Name="SetPluginVersion" BeforeTargets="AddGeneratedFile" DependsOnTargets="MinVer">
    <PropertyGroup>
      <PlainVersion>$(MinVerMajor).$(MinVerMinor).$(MinVerPatch)</PlainVersion>
      <BepInExPluginVersion>$(PlainVersion)</BepInExPluginVersion>
    </PropertyGroup>
  </Target>

  <Target Name="SaveVersionAndNameToFiles" DependsOnTargets="SetPluginVersion">
    <WriteLinesToFile File="$(ProjectDir)dist/name.txt" Lines="$(AssemblyName)" Overwrite="true" />
    <WriteLinesToFile File="$(ProjectDir)dist/version.txt" Lines="$(PlainVersion)" Overwrite="true" />
  </Target>

  <Target Name="PackThunderstore" DependsOnTargets="NetcodePatch;SetPluginVersion;SaveVersionAndNameToFiles" AfterTargets="PostBuildEvent" Condition="$(Configuration) == 'Release'">

    <MakeDir Directories="$(ProjectDir)../assets/bundles" Condition="!Exists('$(ProjectDir)../assets/bundles')" />

    <Exec Command="dotnet tcli build --config-path &quot;$(ProjectDir)../assets/thunderstore.toml&quot; --package-version $(PlainVersion)" />

  </Target>

  <!-- thunderstore publish -->
  <Target Name="PublishThunderstore" DependsOnTargets="SetPluginVersion;SaveVersionAndNameToFiles">
    <Exec Command="dotnet tcli publish --config-path &quot;$(ProjectDir)../assets/thunderstore.toml&quot; --file &quot;$(ProjectDir)dist/*-$(MinVerVersion).zip&quot;" />
  </Target>

  <!-- zipping the .dll alone for curseforge release -->
  <Target Name="ZipCurseForge" AfterTargets="PackThunderstore">
    <MakeDir Directories="$(ProjectDir)dist/output/" Condition="!Exists('$(ProjectDir)dist/output/')" />
    <Copy SourceFiles="$(ProjectDir)bin/Release/netstandard2.1/$(AssemblyName).dll" DestinationFiles="$(ProjectDir)dist/output/$(AssemblyName).dll" />

    <ZipDirectory SourceDirectory="$(ProjectDir)dist/output/" DestinationFile="$(ProjectDir)dist/curseforge.zip" Overwrite="true" />
  </Target>

</Project>