# all directories are relative to the location of this toml file (/assets/thunderstore.toml)
[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "pacoito"
name = "LethalLevelLoaderUpdated"
description = "[Deprecated] A Custom API to support the manual and dynamic integration of all forms of custom content in Lethal Company. (v73 Compatible)"
websiteUrl = "https://github.com/pacoito123/LC_LethalLevelLoader"
containsNsfwContent = false

[package.dependencies]
IAmBatby-LethalLevelLoader = "1.6.0"
BepInEx-BepInExPack = "5.4.2304"
Evaisa-FixPluginTypesSerialization = "1.1.4"
MaxWasUnavailable-LethalModDataLib = "1.2.2"

[build]
icon = "../icon.png"
readme = "../README.md"
outdir = "../dist"

[[build.copy]]
source = "../LethalLevelLoader/bin/Release/netstandard2.1/LethalLevelLoader.dll"
target = "/BepInEx/plugins/"

# [[build.copy]]
# source = "../LethalLevelLoader.Patcher/bin/Release/netstandard2.1/LethalLevelLoader.Patcher.dll"
# target = "/BepInEx/patchers/LethalLevelLoader/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../LICENSE.md"
target = "/"

[publish]
communities = [ "lethal-company", ]